### ISSUE TITLE
Possible to return function object rather than evaluate?

### ISSUE THREAD

**Issue by bkpgh** [danthedeckie/simpleeval#116]
Can simpleeval return a function object to be evaluated later, perhaps repeatedly, based on current values of component functions and arguments? If not, is this a relatively easy enhancement? Thanks.

**Comment by TheTechRobo** [comment]
Maybe this could be done by returning a lambda, I doubt this would be _too_ hard...

**Comment by danthedeckie** [comment]
See #115
