### ISSUE TITLE
Possible to generate RPN from AST.

### ISSUE THREAD

**Issue by lefsky** [danthedeckie/simpleeval#118]
I need an expression evaluator that will generate the proper evaluation sequence in RPN for further processing into server side function calls. Is this possible with simpleeval or could it added with minimal work?

**Comment by danthedeckie** [comment]
I think that simpleeval is not the right choice for that problem.

There might be a way to do that - but it would involve such a lot of hackery that it's probably not worth it.

However, you may be able to find interesting ideas in simpleeval to help you.

If you wrote a parser for RPN that produced a python AST then you could use potentially use simpleeval to sandbox it and run it (using the `.eval(..., previously_parsed=ast)` syntax in #115 .
