### ISSUE TITLE
while shortcode seems endless loop

### ISSUE THREAD

**Issue by shiyuleixia** [danthedeckie/simpleeval#128]
when I ran the "while" shortcode example in the manual:
[set my_var]3[/set]
[while "my_var < 10"]
	Output
	{sets my_var="my_var + 1"}
[/while]

it just did't return anything,and then my WebUi seemed no working and the CPU Usage is 100 percent,and I must restart it

**Comment by danthedeckie** [comment]
Hi @shiyuleixia  - which project is this you are talking about?

The example you listed looks like it's for some kind of web / templating system, rather than anything directly related to `simpleeval`?
