### ISSUE TITLE
Expression does not give expected result

### ISSUE THREAD

**Issue by sawan** [danthedeckie/simpleeval#13]
Consider the following:

```python
out = True
position = 3
expr = '(out and position <=6 and -10) or (out and position > 6 and -5) or (not out and 15)'

simple_eval(expr, names={'out': True, 'position': 3} )
```
gives the result 
> True

This is wrong. Using
```python
eval(expr)
```
we get the **correct** result:
> -10

Is this a bug? Or intentional?

**Comment by danthedeckie** [comment]
hm. I think it could be a bug.  it can actually be demonstrated even simpler:

`False or 42`
> 42

`simple_eval("False or 42")`
> True

**Comment by danthedeckie** [comment]
I think I fixed it in that commit. So I'll call it closed. If I'm wrong, please re open it!
