### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by amyasnikov** [danthedeckie/simpleeval#140]
Last activity in the repo was more than 1 year ago.

Is there any plans to fix current issues and make new release? For example, there are two merge requests for #57 from two different authors, but none of them are accepted/merged.

**Comment by kurtmckee** [comment]
@danthedeckie I recommend closing this issue. It's not a feature request or bug report.

**Comment by smurfix** [comment]
Well, arguably the bug is that there are a couple of open unresolved PRs that (by now) cause unrelated packages to break their testsuites, because of the `DeprecationWarning`s fixed by PR #136 if nothing else.

Time to expand the range of maintainers, I'd recommend (and volunteer).

**Comment by danthedeckie** [comment]
I would love extra help maintaining this.

I kind of want to get a 1.0 out the door and then think about changing how it's organised totally, get more people involved properly rather than me being the thing slowing it all down.

Sorry for not being better responsive over the past few years.
