### ISSUE TITLE
Including non-builtin class in names allows end user to snoop

### ISSUE THREAD

**Issue by perkinslr** [danthedeckie/simpleeval#15]
If the user (source of untrusted code) can get access to a non-builtin function, such as a method defined on a non-builtin class, they can access the functions `func_globals` or `__globals__` property and see everything defined in that function's module.  This includes other imported modules and often leads to access to `sys`, and by extension, `sys.modules`.  This could allow an attacker to find sensitive data (usernames, passwords, PII) by crawling through the list of modules.  Even if the sensitive information is not defined at top level, inspection of function objects will reveal any constants or default arguments used anywhere in the running system.

At a minimum, attribute lookup for attributes beginning with `_` should be denied (plus the special case in python2 to deny func_*).  Ideally, attribute lookup should have a configurable max-depth, or a whitelist of allowed types and classes.

**Comment by danthedeckie** [comment]
Hey @perkinslr - I've pushed a fix (I hope) for that.  What do you think?  Does this resolve this vulnerability fully?
I really appreciate the time you took to report this.  Thanks :-)

**Comment by perkinslr** [comment]
Looks like that will pretty well do it.  I would have it refuse to get anything starting with `_` instead of `__`.  `__` is used for python internals, but `_` is used for any name-mangled private attributes.  I would think private attributes should be disallowed by default.

**Comment by perkinslr** [comment]
Looks like that will pretty well do it.  I would have it refuse to get anything starting with `_` instead of `__`.  `__` is used for python internals, but `_` is used for any name-mangled private attributes.  I would think private attributes should be disallowed by default.

**Comment by danthedeckie** [comment]
Hm. It should probably be library-user configurable. As much as possible, I don't want to introduce needless restrictions on what can be evaluated, but safer defaults do reduce vulnerabilities.

**Comment by danthedeckie** [comment]
I've changed the default to disallowing '_'.  That just makes sense. It's over-ridable if people really need.

**Comment by achen88** [comment]
Why are we disallowing anything starting with just `_`? Don't attributes always start with `__`?

I understand that this is configurable, but disallowing legitimate variable names starting with `_` doesn't seem like ideal behavior to me.
