### ISSUE TITLE
Is `pip` really required at runtime?

### ISSUE THREAD

**Issue by edgarrmondragon** [danthedeckie/simpleeval#155]
Recent update https://github.com/danthedeckie/simpleeval/commit/8d3ac9ab45dc373819fbc8af35f3cd52328cdfa1 made `pip` a runtime dependency of this library.

It doesn't seem to be used anywhere and it brings a new dependency into environments where `simpleeval` is installed.

Can it me removed, or even just moved to an extra or make it a dev dependency?

**Comment by edgarrmondragon** [comment]
I opened a PR: https://github.com/danthedeckie/simpleeval/pull/156

**Comment by danthedeckie** [comment]
Hey @edgarrmondragon -

Thanks so much, and sorry for the mistake.

I've released 1.0.2 with that requirement removed.

https://pypi.org/project/simpleeval/1.0.2/

**Comment by mgorny** [comment]
Thanks!
