### ISSUE TITLE
Expression Evaluation Error

### ISSUE THREAD

**Issue by jolson6** [danthedeckie/simpleeval#16]
Perhaps I am misunderstanding how the expression evaluator should work, but consider the following:

> >>>formula = "0 <= 10 <= 5"
> >>>simple_eval(formula)
>  True

While 0 <= 10 should evaluate to True, 10 <= 5 should not. Perhaps the evaluation is being short-circuited? Is this intentional? 

I also tested this with Python's built in eval function:

> >>>formula = "0 <= 10 <= 5"
> >>>eval(formula)
>  False

**Comment by danthedeckie** [comment]
In general, pretty much everything should evaluate the same as python does it.  So yep, that's a bug.  Thanks for the report!

**Comment by danthedeckie** [comment]
a62bd73 should have fixed it...
