### ISSUE TITLE
Leading space results in IndentationError

### ISSUE THREAD

**Issue by iivvoo** [danthedeckie/simpleeval#17]
I'm using simpleeval for evaluating template expressions, e.g.

```
{{ foo.bar }}
```

Because the engine (https://github.com/iivvoo/ate if anyone's interested ;) aims to be user (programmer) friendly it ignores leading/trailing whitespaces and passes them verbatim to simpleeval which sometimes results in an IndentationError

```
In [1]: from simpleeval import simple_eval
In [2]: simple_eval(" True")
  File "<unknown>", line 1
    True
    ^
IndentationError: unexpected indent
```

This is quite simple to work around but it makes me wonder if there's any need at all for simpleeval to be so strict about whitespace - is any form of indentation actually supported?

**Comment by danthedeckie** [comment]
No, you're quite right.  No indentation is supported at all.  :-)
So it now strips it, as of: e0347ba
Is that all working for you now?
If no one complains, I'll close this next week.
