### ISSUE TITLE
Installing works, but gives ParseError warning

### ISSUE THREAD

**Issue by dominicrodger** [danthedeckie/simpleeval#18]
I just ran:

    pip install simpleeval

It was successfully installed (and works locally), but there was a warning from [line 55](https://github.com/danthedeckie/simpleeval/blob/5fe4da4579fbd4eed4b7cddb15b09950a6178808/simpleeval.py#L55):

    Can't parse docstring in build/lib/simpleeval.py line 55: ParseError: bad input: type=0, value='', context=('', (56, 0))

**Comment by danthedeckie** [comment]
Huh. Interesting.  The code looks valid to me... (OK, it's missing a space after the comma, but that shouldn't raise a ParseError, I'd have thought...)

What (exactly) is giving that warning?  Is it pip itself?  Do you have some kind of extra logging / testing options turned on somewhere?

Which versions of python & pip are you using?  Which OS?

**Comment by dominicrodger** [comment]
Ah - everything's fine with Python 2.7, but not with Python 3.5. Also, it turns out I had a really old version of pip (1.5.4), and it's fine with recent pips (just tested after running ``pip install --upgrade pip``, which gets me pip 9.0.1).

Given all that, I think "closing as irrelevant" is a reasonable response, but I'll leave that up to you!

**Comment by danthedeckie** [comment]
OK. Thanks for the report anyway. :-)
