### ISSUE TITLE
Functions not considered during name lookup

### ISSUE THREAD

**Issue by daveisfera** [danthedeckie/simpleeval#23]
Here's a simple reproducer of the problem:
```
#!/usr/bin/env python3

from simpleeval import EvalWithCompoundTypes

s = EvalWithCompoundTypes(functions={"map": map, "str": str})
print(s.eval("list(map(str, [-1, 0, 1]))"))
```

The fix is to have `SimpleEval._eval_name()` also look in `self.functions` when it can't find node.is in `self.names`. I can submit a pull request once my pending one is closed.

**Comment by daveisfera** [comment]
Here's a patch with the fix and a test case:
```
diff --git a/simpleeval.py b/simpleeval.py
index 1ea25a2..89f2727 100644
--- a/simpleeval.py
+++ b/simpleeval.py
@@ -371,6 +371,9 @@ class SimpleEval(object):  # pylint: disable=too-few-public-methods
                                         ' evaluator'.format(node.id))

         except KeyError:
+            if node.id in self.functions:
+                return self.functions[node.id]
+
             raise NameNotDefined(node.id, self.expr)

     def _eval_subscript(self, node):
diff --git a/test_simpleeval.py b/test_simpleeval.py
index e492d8e..add2ca6 100644
--- a/test_simpleeval.py
+++ b/test_simpleeval.py
@@ -445,6 +445,12 @@ class TestCompoundTypes(DRYTest):
         self.t('not {0: 1}', False)
         self.t('not {0}', False)

+    def test_use_func(self):
+        self.s = EvalWithCompoundTypes(functions={"map": map, "str": str})
+        self.t('list(map(str, [-1, 0, 1]))', ['-1', '0', '1'])
+        with self.assertRaises(NameNotDefined):
+            self.t('list(map(bad, [-1, 0, 1]))', ['-1', '0', '1'])
+

 class TestNames(DRYTest):
     """ 'names', what other languages call variables... """
```

**Comment by danthedeckie** [comment]
I'm not 100% sure about this just yet.  As a functional programmer, yes, of course functions are values and should be considered as such.

From a security point of view - could there be cases where an application using simpleeval could want end-users to be able to call functions without having access to non _hidden attributes?

It's pretty easy to have a names function which has this fallback if explicitly wanted.

Or am I being needlessly paranoid / overthinking things?

**Comment by daveisfera** [comment]
The current checks prevent access to attributes. Here are some examples:
```
print(s.eval("dir(str)")
simpleeval.FunctionNotDefined: Function 'dir' not defined, for expression 'dir(str)'.
```

```
print(s.eval("str.__dict__"))
simpleeval.FeatureNotAvailable: Sorry, access to __attributes  or func_ attributes is not available. (__dict__)
```

And even if you allow dir to be called, then you end up with the check preventing it:
```
print(s.eval("dir(str)", {"dir": dir}))
simpleeval.FeatureNotAvailable: Sorry, access to __attributes  or func_ attributes is not available. (__dict__)
```

So I think it seems safe to allow this and it would probably be worth adding these conditions to the test cases just to be sure that access is not allowed with any future changes.

**Comment by daveisfera** [comment]
Actually, that last test only raises `FeatureNotAvailable` without this change. So, if the user adds `dir()` to the list of functions, then the expression being evaluated can get access to the attributes. But I think that's fine, since it's something that the user has to manually enable and not something that's available out of the box.
If you're ok with this change, then just let me know and I'll submit a pull request.

**Comment by danthedeckie** [comment]
Sure. Sounds good.
