### ISSUE TITLE
Make Eval Class Callable

### ISSUE THREAD

**Issue by danthedeckie** [danthedeckie/simpleeval#25]
so you could do:

    >>> s = SimpleEval()
    >>> s('22 + 20')
    42

which would be rather sweet.

**Comment by dave-nm** [comment]
The way I'm currently using it, I have used the extension capabilities so that I can parse an expression a single time and then call it multiple times to perform the same operation on multiple variables. Here's the very simple code and I think that it could be useful as a general feature:
```
    # Parse the given code into AST
    def parse(self, code):
        self.expr = code

        self._ast = ast.parse(code)

    # Run the parsed code with the variables in names available for use in the code
    def __call__(self, names=None):
        if names:
            self.names.update(names)
        return self._eval(self._ast) 
```

**Comment by danthedeckie** [comment]
Cool idea!  I hadn't thought of doing multiple runs on different data.
I'm exploring this a bit on the Dev branch.

**Comment by ThePlasmaRailgun** [comment]
Couldn't you do
```
    def __call__(self, *args, **kwargs):
        return self.eval(*args, **kwargs)
```

**Comment by chongr** [comment]
Is there still interest in this?  Did anyone ever make a PR?  We also have a use case for this

**Comment by danthedeckie** [comment]
Closing this - I don't believe it's valuable any more.
the cached `parse` stuff covers some of it, and the rest could be easily done as a wrapper class outside simpleeval.

If there are things I've forgotten that are important, please raise a new issue.
