### ISSUE TITLE
Modifying defaults

### ISSUE THREAD

**Issue by fitoprincipe** [danthedeckie/simpleeval#30]
Hi, first of all I want to thank you for the package. It comes very handy to my project. I have forked it, so I'm open to contribute.

I have some questions, what happens if I do:

```
import simpleeval
import math

simpleeval.DEFAULT_FUNCTIONS["sqrt"] = math.sqrt
print simpleeval.simple_eval("sqrt(25)")
```

> \>\>\> 5

It works, but, is that all right? Is it the supposed way I should do it? is there any risk?

**Comment by danthedeckie** [comment]
That does work, but it's not really ideal. :-)
Best is to create a SimpleEval() instance, and modify the functions of just that instance.
The ReadMe should explain how...

**Comment by danthedeckie** [comment]
https://github.com/danthedeckie/simpleeval/blob/master/README.rst#creating-an-evaluator-class

**Comment by fitoprincipe** [comment]
Hi,
Yes I understand that and know how to do it, but as I am writing a module I need to use functions, operators an even names in the whole module. For instance, I add *pi* to the names. That is why to me is easier to add them to the defaults. But I wanted to know if this is "safe", I guess so.

**Comment by danthedeckie** [comment]
Oh, OK.
Well, check the code. It's fairly basic.  And should be safe.
If you're concerned, create a module of your own that wraps SimpleEval, with your own defaults, and expose that to the rest of your application.
