### ISSUE TITLE
Support "decimal" module

### ISSUE THREAD

**Issue by Jellby** [danthedeckie/simpleeval#32]
Would be possible to support the `decimal` module, such that e.g. `simple_eval('0.1+0.2')` gives `0.3` instead of `0.30000000000000004`?

**Comment by danthedeckie** [comment]
You can add this kind of thing yourself trivially:

    import decimal
    import simpleeval

    class DecimalEval(simpleeval.SimpleEval):
        @staticmethod
        def _eval_num(node):
            return decimal.Decimal(node.n)

    decimal.getcontext().prec = 1
    DecimalEval().eval('0.1+0.2')

returns:

    Decimal(0.3)

I'd rather keep simpleeval slim without adding this functionality to the base module.  But it's a cool idea!  Thanks for asking.
