### ISSUE TITLE
safe_lambda

### ISSUE THREAD

**Issue by wagnerc4** [danthedeckie/simpleeval#38]
Hi! maybe this can help:

    def safe_lambda(x, y):
      return lambda z: simple_eval(y, names={x:z})
    
    list(filter(safe_lambda('x', 'x > 2'), [1, 2, 3, 4, 5, 6]))

**Comment by danthedeckie** [comment]
Maybe I'm being dense - but what is this supposed to help with?

**Comment by wagnerc4** [comment]
This was a solution util we can use list comprehensions, for example:

    v = simple_eval("list(filter(safe_lambda('x', 'x > 2'), r))",
                              names={"r":[1, 2, 3, 4, 5, 6]},
                              functions={"list":list, "filter":filter, "safe_lambda":safe_lambda})

Would be nice if we can do this:

    v = simple_eval("[x for x in r if x>2]", names={"r":[1, 2, 3, 4, 5, 6]})

**Comment by wagnerc4** [comment]
This is other example:

v = simple_eval("sum(list(map(safe_lambda('x', 'x[1] if x[0] == 1 else 0'),
r)))",
                names={"r":[[1, 2], [1, 3], [2, 4], [2, 5]]},
                functions={"sum":sum, "list":list, "map":map,
"safe_lambda":safe_lambda})

**Comment by wagnerc4** [comment]
Other example:

    v = simple_eval("sum(list(map(safe_lambda('x', 'x[1] if x[0] == 1 else 0'), r)))",
                    names={"r":[[1, 2], [1, 3], [2, 4], [2, 5]]},
                    functions={"sum":sum, "list":list, "map":map, "safe_lambda":safe_lambda})
