### ISSUE TITLE
Weird behaviour when trying to evaluate a class method chaining

### ISSUE THREAD

**Issue by xaled** [danthedeckie/simpleeval#39]
Hello,
First I want to thank you for this project,
I was trying to evaluate some class method calls using the **method chaining** syntax, but i got a weird result:
my code:
```python
from __future__ import print_function
import simpleeval

class A(object):
    def __init__(self):
        self.a = "0"

    def add(self, b):
        self.a += "-add" + str(b)
        return self

    def sub(self, b):
        self.a += "-sub" + str(b)
        return self

    def __str__(self):
        return str(self.a)

x = A()
print(simpleeval.simple_eval("x.add(1).sub(2).sub(3)", names={"x": x}))
x = A()
print(x.add(1).sub(2).sub(3)) # expected output
```

the output:

> 0-add1-add1-sub2-add1-add1-sub2-sub3
> 0-add1-sub2-sub3

The first line is the output from simpleeval.

**Comment by danthedeckie** [comment]
Hi Xaled,

Awesome, great fix.  May I add this code as a test-case?

**Comment by xaled** [comment]
Yes, of course.
