### ISSUE TITLE
test_simpleeval.py not packaged

### ISSUE THREAD

**Issue by cedk** [danthedeckie/simpleeval#4]
The file test_simpleeval.py is not in the package on PyPI.
It will be good to have it to test if the installation is correct.

**Comment by mbehrle** [comment]
+1. Running the automatic tests for Debian packages fails, because the file is refered to as testsuite in setup.py.

Could you please consider releasing soon with this fix to be able to upload to Debian?

Thanks for simpleeval!

**Comment by danthedeckie** [comment]
@mbehrle Is this ok/working now?  I added the test file to MANIFEST.in a while ago, and the version has gone up several times since then.  I don't know how to test this.

**Comment by cedk** [comment]
For me, the tests works for Gentoo packages since 0.8.5
