### ISSUE TITLE
Include simple built-ins

### ISSUE THREAD

**Issue by robertmlinden** [danthedeckie/simpleeval#43]
Why not allow functions such as `range()`?

**Comment by danthedeckie** [comment]
Including functions is trivial.

SimpleEval is designed as a library to do all the parsing and evaluating - but you as the library user still *need* to think about what functionality you want to give access to.

Say you did want to include-by-default some basic functions:

Where would you draw the borders or what's allowed or not?

Presumably all the type functions, `str`, `int`, etc.  Then I guess you'd have to include `list` and the other composite type functions but only in the evaluator with composite types.

if `range` or `xrange` also everything secure in `__builtins__`, and maybe also some modules such as `math`?

Speaking of  `range`- you'd need to include your own safe version of it that respected the `MAX_` values...

I'd much rather keep SimpleEval simple - without any builtins, and let people include what they think is appropriate for their specific application.
