### ISSUE TITLE
README doesn't render correctly on PyPI

### ISSUE THREAD

**Issue by lubieowoce** [danthedeckie/simpleeval#45]
Hi! This is what the PyPI page looks like to me (Chrome/Android):

![storage emulated 0 firespeed org resizeimage 612-452-1538742958902](https://user-images.githubusercontent.com/13698226/46535557-152cfc80-c8ac-11e8-9c34-65c0767751f1.jpeg)

IME with markdown, adding a `long_description_content_type='<your_format>'` to your `setup(...)` should make the page render correctly. (I'm not sure if it's supposed to be `'rst'` or `'reStructuredText'` though.) You might have to update your setuptools, some older versions don't recognize that parameter.

**Comment by danthedeckie** [comment]
Thanks - I've added in (I think) the correct format now `'text/x-rst'` according to the spec.  It checks out with twine, so next time I bump the version on pypi it should correct itself.
