### ISSUE TITLE
Lambda application causes crash instead of `FeatureNotAvailable`

### ISSUE THREAD

**Issue by lubieowoce** [danthedeckie/simpleeval#46]
I ran into this crash when investigating `safeeval`'s resiliency against lambda-based attacks.
#### Platform:
```
Python 3.6.5 (default, Apr  3 2018, 21:02:01)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
```
I'm using the Android app Termux, so the environment is a bit unusual, but this doesn't look like a platform-specific crash. Maybe this is caused by some change in `ast` on Python 3.6?

#### Code:
```python
>>> import simpleeval
>>> s = simpleeval.SimpleEval()
>>> s.eval('(lambda x: x+1)(3)')
```
#### Expected result:
```python
Traceback (most recent call last):
  ...
  simpleeval.FeatureNotAvailable: Sorry, Lambda is not available in this evaluator
```
#### Actual result (crash):
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<python path>/site-packages/simpleeval.py", line 283, in eval
    return self._eval(ast.parse(expr.strip()).body[0].value)
  File "<python path>/site-packages/simpleeval.py", line 294, in _eval
    return handler(node)
  File "<python path>/site-packages/simpleeval.py", line 353, in _eval_call
    func = self.functions[node.func.id]
AttributeError: 'Lambda' object has no attribute 'id'
```

`s.eval('lambda x: x')` correctly raises `FeatureNotAvailable`, only a lambda application causes this problem.

**Comment by danthedeckie** [comment]
Huh - now that's a weird one.

Good catch.

Please continue digging for problems!

**Comment by lubieowoce** [comment]
I found one more potential vulnerability – you can access non-whitelisted classes through `SomeClass.mro()`, you might want to block that. Other than that, blacklisting lambdas, `__dunder__` methods/attributes and list comprehensions¹ seems very effective, I couldn't come up with any hacks without those. 

¹ list comprehensions can be used to bind names: `[... for x in (foo(),)]` ≈ `let x = foo() in ...`), so you could use them to create a self-referencing object and call something on it to get a crash via infinite recursion. As an example, this expression yields a list that contains itself: `[(x.append(x), x)[-1] for x in ([],)][0]` ≈ `x = []; x.append(x); x`

**Comment by danthedeckie** [comment]
Thanks! That's great!

I've blacklisted the 'mro' method for now (man, I'm learning a lot about Python through this project), and also added in a proper exception for the lambda crash.

The current git HEAD does actually have list comprehension support added to the `EvalWithCompoundTypes` class, but with an explicit limit on how many recursions it will do.

Could you poke around with that and see if you can find a way to by-pass it, and if so, raise a new issue?

**Comment by lubieowoce** [comment]
I'll check it out! (pun partially intended)
