### ISSUE TITLE
Side effects on names

### ISSUE THREAD

**Issue by JCavallo** [danthedeckie/simpleeval#47]
Hi,

I've noticed that the ``names`` dictionary provided to ``simple_eval`` was actually modified here:

https://github.com/danthedeckie/simpleeval/commit/3aa36f3360584957bc2247f911dbb3ecaa6d051a

It is a difficult side-effect to detect, so I would like to know if it is the expected behavior (meaning one should always copy actual data passed to names) or a bug to fix.

**Comment by danthedeckie** [comment]
Ouch - yes, that's a bit unfriendly, isn't it.

Thanks for noticing that.  I'll pop the 'None' definition into the `DEFAULT_NAMES` dict instead.

The `names` dictionary shouldn't ever be messed up by simpleeval - it might be by functions define and give to simpleeval - but that's another story...

**Comment by JCavallo** [comment]
@danthedeckie Thanks for the quick fix ! Any idea on when a 0.9.7 could be released ?

**Comment by danthedeckie** [comment]
There's quite a few big changes - adding comprehensions is a biggie - so I wanted a little more time to test, and let other clever people try and pick holes in it before 0.9.7....

**Comment by JCavallo** [comment]
No problem, I was just wondering
