### ISSUE TITLE
Exceptions during list comprehensions leak local variables

### ISSUE THREAD

**Issue by Birne94** [danthedeckie/simpleeval#52]
**Example code:**

```python
import ast

from simpleeval import EvalWithCompoundTypes

e = EvalWithCompoundTypes()

try:
    print(e.eval('[x if x == "2" else y for x in "123"]'))
except Exception as exc:
    print(exc)
print(e.nodes[ast.Name])
print(e.eval('x'))

```

**Result:**
```
'y' is not defined for expression '[x if x == "2" else y for x in "123"]'
<function EvalWithCompoundTypes._eval_comprehension.<locals>.eval_names_extra at 0x1098f91e0>
1
```

**Expected Result:**

The second print statement should print something like `<bound method SimpleEval._eval_name of <simpleeval.EvalWithCompoundTypes object at 0x10bf2f860>>` while the second evaluation should raise a `NameNotDefined` exception.

**Solution:**

The `_eval_comprehension` method changes the evaller for the `ast.Name` node, but does not reset it in case of an exception. This can be easily solved by wrapping the call to `do_generator` into a `try...finally` construct.

**Comment by danthedeckie** [comment]
Good catch @Birne94 .  Thanks!

**Comment by danthedeckie** [comment]
It's possible there are other issues around related to this concept - I'd not really been thinking much of SimpleEval objects being used multiple times, even after exceptions.  My use cases usually involve "If there's an exception, stop everything until the user sorts it out".
So there could be other places there are similar problems.
