### ISSUE TITLE
LICENCE in pypi tarball

### ISSUE THREAD

**Issue by pgajdos** [danthedeckie/simpleeval#55]
Hi,
could you please ship licence file along with tarbal as usual in opensource projects?
Thanks for considering

**Comment by sharkcz** [comment]
Seems it got dropped at some point, 0.9.6 source archive contains a LICENSE file.

**Comment by pgajdos** [comment]
Thanks!

**Comment by danthedeckie** [comment]
Should be back now.  Sorry for the delay!
