### ISSUE TITLE
Feature request: provide support for DictComp

### ISSUE THREAD

**Issue by Reskov** [danthedeckie/simpleeval#57]
Such code is not support by `EvalWithCompoundTypes`
```
{i:i for i in range(3)}
```

Basically, it is should be easy to support such functionality with something like that https://github.com/Reskov/simpleeval/commit/695bb684fff24af7eab47505f8438261911f109b

I can do more tests and prepare PR if you agree in general

**Comment by danthedeckie** [comment]
This would be really cool to add

**Comment by amyasnikov** [comment]
+1 for this feature request. DictComp is really a missing thing for this cool library.
@Reskov could you prepare a PR? As I see in the previous comment @danthedeckie is ready to accept it (please correct me if I'm wrong)

**Comment by Reskov** [comment]
@amyasnikov Not sure. Personally, I am not interested in this anymore. 😞 And there was already [PR #62](https://github.com/danthedeckie/simpleeval/pull/62).

**Comment by danthedeckie** [comment]
Should be fixed in 1.0.0
