### ISSUE TITLE
[feat]FeatureNotAvailable: Sorry, Lambda is not available in this evaluator

### ISSUE THREAD

**Issue by shouldsee** [danthedeckie/simpleeval#59]
Is there any plan on adding a method processing `ast.Lamba` ?

**Comment by danthedeckie** [comment]
Technically it's possible.  I (personally) have no plans for it.
I think as a general thing, it's too flexible to be generally useful (I could be wrong!)
It should be reasonably easy to subclass the evaluator and make a lambda supporting one if you want to.
