### ISSUE TITLE
Help is not included when using pyinstaller

### ISSUE THREAD

**Issue by shughes-uk** [danthedeckie/simpleeval#69]
I'm having an issue when creating a python binary using Pyinstaller. It does not include the ```site``` module , which is where ```help``` comes from. This results in a NameError when importing simpleeval. As including ```site``` seems like it would cause Pyinstaller significant issues it might be wise to check for it's existence before adding it to your excluded keywords list in simpleeval.

The relevant code is ```DISALLOW_FUNCTIONS = {type, isinstance, eval, getattr, setattr, help, repr, compile, open}```

Here's a pyinstaller issue I was able to find that is related.

https://github.com/pyinstaller/pyinstaller/issues/4448

If you feel this is a pyinstaller issue I can recreate this issue over there.

**Comment by danthedeckie** [comment]
Nice catch @shughes-uk !  And awesome creating a PR for it too 😄 

I put a suggested change in the PR.

**Comment by Toilal** [comment]
Hi @danthedeckie, could you perform a release including this fix ?
