### ISSUE TITLE
How to change MAX_POWER limit without edit simpleeval source code

### ISSUE THREAD

**Issue by JavierFuentes** [danthedeckie/simpleeval#77]
Hello,
congratulations on this fantastic library.

It has allowed me to develop a generic function with the following signature:

```python
def calc_model (formula, ** kargs)
```

The native function `eval (formula, kargs)` was giving me an error when the formula contained functions like `math.log10 (x)` even after importing it.

Embedding the import just before the formula was not the solution either:

```python
if ('math' in formula):
         formula = 'import math; '+ formula
```

Finally, I had the solution with **simpleeval** defining a specific lambda function:

```python
log10_lambda = {"log10": lambda x: math.log10(x)}
result = simple_eval (formula, names = kargs, functions = log10_lambda)
```

### MY QUESTION IS
How can I increase or even completely disable the MAX_POWER limit value without editing the library source code?

I have some formulas that need it

Thanks in advance.

**Comment by JavierFuentes** [comment]
Hello again,
In case it helps anyone, **I have finally solved the problem I had when using `eval( )`** when in the formulas there are external references like math ...

Simply, **I have injected joined with my kargs parameters all the *globals( )* variables in a single dictionary**:

```python
result = eval( formula, {**kargs, **globals()} )
```

**Another solution using `exec( )`** is this, but all formulas need to have a RESULT variable we cand find en get its value:

```python
if ( '=' not in formula ):
     formula = 'RESULT = ' + formula
        
loc = {}
exec( formula, {**kargs, **globals()}, loc )
result = loc['RESULT']
```

**Comment by n1ngu** [comment]
This was documented long ago https://github.com/danthedeckie/simpleeval#limited-power

Didn't that work for you?

**Comment by danthedeckie** [comment]
If you want to disable the safety features, you can replace the `safe` versions of the operators with the original ones from `operator`.

Something like:

```python
import operator
import ast
import simpleeval

ops = simpleeval.DEFAULT_OPERATORS.copy()
ops[ast.Mult] = operator.mul

simpleeval.simple_eval(... operators=ops)
```
Check the operator module https://docs.python.org/3/library/operator.html
