### ISSUE TITLE
Support implied multiply

### ISSUE THREAD

**Issue by jeffreyscottgraham** [danthedeckie/simpleeval#80]
Can support by added for the implied multiplication, for example:
  "2(3+4)"

If not, how can a random equation be edited at runtime to insert the '*' ?

**Comment by n1ngu** [comment]
IMHO simpleeval as a library should never support such a feature. It is a safe replacement for python's eval builtin, and it should only accept valid python sourcecode.

If you are building a calculator / formula parsing application and you want to support syntax sugar beyond bare python syntax, that's on you!

**Comment by danthedeckie** [comment]
That's a really interesting idea - having a library that did that would be cool.
 And you might be able to figure out a way to do that with extending simple eval - but it's not going to be part of core.
It deviates too much from regular python code.
