### ISSUE TITLE
Problem when building using simpleeval 

### ISSUE THREAD

**Issue by LBeghini** [danthedeckie/simpleeval#88]
I have a project that I wanted to build to create a release. I've tried with py2exe and PyInstaller.  
However, always after the building, it throws an error that says: 
```
   File "simpleeval.py", line 116, in <module>
NameError: name 'help' is not defined
[39588] Failed to execute script app
```

I was able to solve this by adding:
```python
def help():
    pass
```
right above the definition of `DISALLOW_FUNCTIONS`, that was at the line 116.

I only did it because I've found another person with the same problem, that described this solution in [this site](https://www.programmersought.com/article/15643835605/).

It would be possible to add this in a release? Because the program works perfectly just with this little modification. But it is annoying to add this always when I want to build the project.  

I don't know if there's another person that faced the same problem and has a better way to solve this. If so, I would like to know.

**Comment by n1ngu** [comment]
So, this is also pending on https://github.com/danthedeckie/simpleeval/issues/83

**Comment by LBeghini** [comment]
It worked like a charm.
